### ISSUE TITLE
Don't require two-factor authentication for logins from specific IPs

### ISSUE THREAD

**Issue by leonardomarino** [tweakier/duo_auth#3]
Is it possible to add two-factor authentication exceptions for specific IP addresses or ranges?

**Comment by tweakier** [comment]
Hi Leonardo,

At the moment the plugin itself does not support this function, however you can look into implementing this feature!

You can however override 2 factor authentication for certain users from your integration settings in Duo Security admin panel if this helps?

**Comment by leonardomarino** [comment]
Thanks for your message @tweakier, could you give me some pointers on how and where to implement this functionality and I will give it a try? Something like having IPs or IP ranges in the configuration file and if there is a match then duo is override.

**Comment by tweakier** [comment]
I will push something to the repo very soon, later on today most likely.
The code will be something along the lines of adding the following code to login_after function 

if(in_array($_SERVER['REMOTE_ADDR'], $this->get('2FA_OVERRIDE'))) {
                        $_SESSION['_Duo_2FAuth'] = True;
                        header('Location: ?_task=mail');
                }

and adding a new variable (2FA_OVERRIDE) in the config file with the IPs to whitelist 
$rcmail_config['2FA_OVERRIDE'] = array("x.x.x.x", "y.y.y.y");

have a play around and see what you can do and in the meantime I'll polish up my code and push it to the repo

**Comment by leonardomarino** [comment]
This works great. I just tested it from different IP addresses and works like a charm.
